name = "Create Forge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1fb86fe87a6f3b147e1e7ba9aa9f97540c2bd921dcb4c6dfd581fe5d1767e455"

[versions]
forge = "40.1.60"
minecraft = "1.18.2"
