name = "Create Forge"
version = "1.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7d10431f37b49967396a1db8b2bb4161f42b3bca111d7260a4efec3c18dd255b"

[versions]
forge = "40.1.60"
minecraft = "1.18.2"
