name = "Create Forge"
version = "1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fc017a03ad7164b123738e4ad26b873f240bb013d234f4e2c63dd01c8b969f4c"

[versions]
forge = "40.1.60"
minecraft = "1.18.2"
