name = "Create Forge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d28021176c498f80cdda14a7ef2b04e7c6fb7cad5a19ae72a9f55e36a6e9335f"

[versions]
forge = "40.1.60"
minecraft = "1.18.2"
