name = "Create Forge"
version = "2.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "02bcc24f9afc21bdbdb744498f0882c60d3641f17545d53042b208785b694a3f"

[versions]
forge = "40.1.60"
minecraft = "1.18.2"
