name = "Create Private"
author = "squeek502"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7e19717f40b93fc0c7afe20b4bb0da44b11453c9443552792c9cda0b9b304856"

[versions]
forge = "40.1.73"
minecraft = "1.18.2"
