name = "Create Bruteforce"
author = "Alfred"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9a782c9f077e5e39e53843e40b7bee18ab59f090f3758f2e74afff4a1e59832c"

[versions]
forge = "40.1.73"
minecraft = "1.18.2"
