name = "Create Forge"
version = "2.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c743b70de4a8d85de93c9d84139139492e56db96dc5e659edf2cbecfdfbf200e"

[versions]
forge = "40.1.60"
minecraft = "1.18.2"
