name = "Create Bruteforce"
author = "Alfred"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eed000d8267955166427fc63cda6aa735bb965f154c2a77774086fbd39adff4d"

[versions]
forge = "40.1.73"
minecraft = "1.18.2"
