name = "Create Bruteforce"
author = "Alfred"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b596f337308984b703c2234513eb40e2e81d25ef9cb51b351a342130585157ff"

[versions]
forge = "40.1.73"
minecraft = "1.18.2"
