name = "Create Forge"
version = "2.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4c4ef3c608194ebdf7fd8b1255defe90208c9c699764a083e992ab31e97d642d"

[versions]
forge = "40.1.60"
minecraft = "1.18.2"
