name = "Create Private 0.2"
author = "squeek502"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b86a5ccbbe0237ebcd9be20e828acbde0eca8b0b7aa727c1f80d9b2d8641638f"

[versions]
forge = "40.1.73"
minecraft = "1.18.2"
