name = "Create Priv"
author = "Alfred"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "76cde69b739bfdfc6c8590224c17f576236fb3f7274cc85d05560079e3397c3e"

[versions]
forge = "40.1.73"
minecraft = "1.18.2"
