name = "Create Bruteforce"
author = "Alfred"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fbe4d244015add0adc202fc95885ad28a02eed1038dabdf19292eb8eb4be5579"

[versions]
forge = "40.1.73"
minecraft = "1.18.2"
