name = "Create Bruteforce"
author = "Alfred"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c0ff1584c89a2bf1f6b84b9aaf6baa7116325fabdd5d50696d9fb3f891792419"

[versions]
forge = "40.1.73"
minecraft = "1.18.2"
