name = "Create Bruteforce"
author = "Alfred"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7dcce7c0965858d4e5c51eeab386393b0c52f0cba4b0fcfc3d53219bc299450a"

[versions]
forge = "40.1.73"
minecraft = "1.18.2"
