name = "Create Bruteforce"
author = "Alfred"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "323eb6316c8c3713883cd8366e2dbb318ae64a0c6d01e061762b1a1168db3e73"

[versions]
forge = "40.1.73"
minecraft = "1.18.2"
