name = "Create Forge"
version = "3.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c3db1dba61ff9f2fa53e9edc1469c27ec6a1509a21e278f2bccaa544887d7a64"

[versions]
forge = "40.1.60"
minecraft = "1.18.2"
